export const UNHAPPY = 1;
export const NEUTRAL = 5;
export const HAPPY = 10;

export const ROUTE_UPDATED = "ROUTE_UPDATED";
export const ROUTE_LOAD_SUCCESS = "ROUTE_LOAD_SUCCESS";

export const TROMBINO_CREATE = "TROMBINO_CREATE";
export const TROMBINO_CREATED = "TROMBINO_CREATED";
export const TROMBINO_LOAD = "TROMBINO_LOAD";
export const TROMBINO_LOADED = "TROMBINO_LOADED";
export const TROMBINO_PEOPLE_FORM_LOAD = "TROMBINO_PEOPLE_FORM_LOAD";
export const TROMBINO_PEOPLE_FORM_LOADED = "TROMBINO_PEOPLE_FORM_LOADED";
export const TROMBINO_ADD_PEOPLE = "TROMBINO_ADD_PEOPLE";
export const TROMBINO_PEOPLE_ADDED = "TROMBINO_PEOPLE_ADDED";
